### ISSUE TITLE
features

### ISSUE THREAD

**Issue by bjenmonk** [ahmetdogukankonuk/dashboard#1]
Hi 
Can you add dark mode and toggle to switch between dark and normal mode? is it possible to change the sidebar to subtle color?

**Comment by ahmetdogukankonuk** [comment]
Hey, yes i can add a dark mode, it will be done probably this weekend. And it is possible to change the sidebars color, you just need to go to dashboard > css > style.css > 
`:root{
  /* Theme Colors */
  --theme-color: #03045e;
  --theme-light-color: #90e0ef;
  --bg-color: #fafbfe;
  --second-theme-color: #caf0f8;
  
  /* Font & Typography  */
  --body-font: 'Nunito', sans-serif;
  --normal-font-size: 1rem;
  --normal-letter-space: 1px;
}`
here you can change the color code however you want. You may want to check this website for cool color pallettes [coolors.co](https://coolors.co/palettes/trending)

**Comment by ahmetdogukankonuk** [comment]
Hey, yes i can add a dark mode, it will be done probably this weekend. And it is possible to change the sidebars color, you just need to go to dashboard > css > style.css > 
`:root{
  --theme-color: #03045e;
  --theme-light-color: #90e0ef;
  --bg-color: #fafbfe;
  --second-theme-color: #caf0f8;
  --body-font: 'Nunito', sans-serif;
  --normal-font-size: 1rem;
  --normal-letter-space: 1px;
}`
here you can change the color code however you want. You may want to check this website for cool color pallettes [coolors.co](https://coolors.co/palettes/trending)

**Comment by bjenmonk** [comment]
thanks

**Comment by bjenmonk** [comment]
thanks

**Comment by ahmetdogukankonuk** [comment]
Hey, i just wanted to let you know that Dark Mode has been added, sorry for latency. I hope you'll like it.
